# Generated by Django 4.0.1 on 2022-05-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
