# Generated by Django 4.0.1 on 2022-05-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_newslatter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslatter',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
