# Generated by Django 4.0.1 on 2022-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_contact_message_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='rpoid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='rppid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='rpsid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
