# Generated by Django 4.0.1 on 2022-05-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_alter_checkout_rpoid_alter_checkout_rppid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='pic',
            field=models.ImageField(blank=True, default='noimage.png', null=True, upload_to='images'),
        ),
    ]
